### ISSUE TITLE
Need solution for overlapping subnet in both side of IPsec tunnel.

### ISSUE THREAD

**Issue by ChienliMa** [BU-NU-CLOUD-SP16/cloud-gateway#4]
First, we need to setup such environment( tunnel with all ends in same subnet ). Then we need to search for solution and try to solve it.

Hint: One possible solution is to do a NAT at both side of the network.

**Comment by rahulbahal7** [comment]
I have added myself to this card on trello. Will work with you on this issue.

**Comment by singhay** [comment]
NAT would be a good idea, its flexible too!

**Comment by ChienliMa** [comment]
#### A possible Solution for Overlapping Subnet(#4) and Internet Traffic routing(#3)

##### Problem description:
1. OpenSwan doesn' t support site-to-site VPN with overlapping subnet space, because in this case it will have no idea where to forward packets. 
2. We would like to direct all traffic(including internect) traffic in public cloud in private cloud. A simple setting of rightsubnet=0.0.0.0/0 seems to solve this problem. Yet last time we do this, we lost connection with our machine and we can even ssh into it at the other side of the tunnel. Although it did response to ping and we can tell that port 22 is listening.

##### Analyse of problem:

Overlapping left/right subnet can be solved be doing a NAT before/after IPsec. However, setting right subnet to 0.0.0.0/0 will make OpenSwan out of control(lost connection). A natural idea is to create a sandbox to run OpenSwan so that we can still have our normal connection even OpenSwan crashed. A way to do this is to create a virtual interface and let OpenSwan listen to that interface, i.e. only handle packet pass through that interface.

##### Solution

To solve the problem of overlapping subnet, we can have a PreRouting NAT to translate IP in remote subnet to a virtual subnet and a PostRouting NAT to translate virtual subnet back to local subnet.

A virtual subnet is a subnet space that its IPs have one-to-one relationship with the IPs we are using in our subnets, and not overlap with our subnet space. This subnet is only use for tunnel transitions. In other words, if a packet is sent to remote overlapping subnet, it's destination will be translate to virtual subnet. And the IPsec service will be able to distinguish these packet from local traffic and send it to correct tunnel. Vice versa in receive side.

---

To solve the problem of Internet traffic routing, we simple route 0.0.0.0/0 to IPsec interface. However, to secure our normal connection, we also set the public IP for remote access(public IP of admin) to be forward directly. Because route table will match rules with longest prefix, we can make sure that our connect won't be crashed be OpenSwan.

Also, by forward local traffic directly, we wont have trouble of left subnet space overlapping with 0.0.0.0/0.

---

Here's a diagram that describe this process, click to enlarge:
![Solution](https://lh3.googleusercontent.com/KnQUzTCKFs9AZxW_uxsaSKFFhsHIcMJn7uB6CVFaA2cJFm3mUNvOvW3lUV4ZItMdwcdryy9RaiJncEbkO7jpwtuHUZL2jB8GvajIkcH5MZbo3LfZhg4QlpsmqyjvlCVvDHptDd7wcfUDbus_RjbTgASGE4sNEWLBgyi_8_jm1AF8yZ7r1cH2GDin1AX0xjAVdZ5nPXYZBbbyKKW_nH1N7I5j87a-o_gf1cnnLWlzR2GyXkIMgTsY6tBOxNYmaOqDls0anEj3SZewtJbKaFKH8rIBxoarG_iSXUoXzf8hT0f9ks-EaUCGdLk8bgo3ag9QShbl2li7SThpJbT_qnxikMjAODE5sBfXmpx_-7w3bGhgCQD6SIG-6Mmq3FM7H10RTamCMxj_kXs0oefJ2J3ruIwREB70udI6-9k3EUltW_Vhz394FKeikekJQDM-JtOHBPhdx_oSVYnN8DdrdobydcvQ5wOfNEweV-aN4HKWyokqPC3cwGqvFG5jvVdQPuIw2C5fZx5AtDBcZkpk4NR0EII3JSyag2H_Msw_NhrwT2pqd9IMFhXIE9MUDgR2VV7yJ_TP=w1114-h580-no)

##### Possible defect or existing problem of this solution
1. Not sure whether OpenSwan can listen to virtual interface, and how to configure it.However, we can setup IPsec in virtual interface using ip-xfrm manually.
2. The loop formed by virtual interface may lower performance.
3. A description from OpenSwan show that OpenSwan possibly support overlap IP, but no  more other documentation

```
overlapip
a boolean (yes/no) that determines, when *subnet=vhost: is used, if the virtual IP claimed by this states created from this connection can with states created from other connections.
Note that connection instances created by the Opportunistic Encryption or PKIX (x.509) instantiation system are distinct internally. They will inherit this policy bit.

The default is no.

This feature is only available with kernel drivers that support SAs to overlapping conns. At present only the (klips)mast protocol stack supports this feature.
```

##### Materials helpful to understand this post:
1. To be added.
